### ISSUE TITLE
STT0003: Parse metadata from Catalog (5)

### ISSUE THREAD

**Issue by spsither** [OpenPecha/stt-catalog-merger#6]
### Description
The metadata for all the departments exist in various formats in their catalog Google Sheets. We need scripts to parse those sheets and get all the metadata associated with audio files.

### Completion Criteria
Get the metadata in the TSV/CSV file ready to be consumed on evaluation of the model.

---
### Implementation Plan 

![Image](https://github.com/OpenPecha/stt-catalog-merger/assets/52191545/203d74d2-fc1d-44f8-8bb7-c18eb1428df2)

### Subtasks
- [x] set google sheet api and authentication
- [x] divide the main google csv files into departments wise csv file
- [x] script to parse google sheet and return df of google sheet
- [x] script to merge the deparment csv files with corresponding google sheet 
- [x] merge all departments csv to main file.
- [x] write test cases

**Comment by gangagyatso4364** [comment]
additional subtask of creating a meta data dictionary containing the columns to be added in main csv file 
for each department google sheets.

**Comment by gangagyatso4364** [comment]
i have to reformat the google sheets by deleting unnecessary columns which do not contribute to the data information gain.

**Comment by gangagyatso4364** [comment]
split the deparment csv file into different parts if the file name id format differs.
